config/routes.rb
Go2::Application.routes.draw do
  resources :atividades

  devise_for :usuarios

  resources :tarefas

  root :to => "inicio#index"

end

app/models/atividade.rb
class Atividade < ActiveRecord::Base
  belongs_to :usuario

  validates_presence_of :nome, :descricao

  attr_accessible :descricao, :nome
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body


  has_many :atividades
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController

  before_filter :authenticate_usuario!

  # GET /atividades
  # GET /atividades.json
  def index
    @atividades = Atividade.all :conditions => {:usuario_id => current_usuario.id}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @atividades }
    end
  end

  # GET /atividades/1
  # GET /atividades/1.json
  def show
    @atividade = Atividade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @atividade }
    end
  end

  # GET /atividades/new
  # GET /atividades/new.json
  def new
    @atividade = Atividade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @atividade }
    end
  end

  # GET /atividades/1/edit
  def edit
    @atividade = Atividade.find(params[:id])
  end

  # POST /atividades
  # POST /atividades.json
  def create
    @atividade = Atividade.new(params[:atividade])
    @atividade.usuario_id = current_usuario.id rescue nil

    respond_to do |format|
      if @atividade.save
        format.html { redirect_to @atividade, notice: 'Atividade criada com sucesso.' }
        format.json { render json: @atividade, status: :created, location: @atividade }
      else
        format.html {
          flash.now[:error] = @atividade.errors
          render action: "new"
        }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /atividades/1
  # PUT /atividades/1.json
  def update
    @atividade = Atividade.find(params[:id])

    respond_to do |format|
      if @atividade.update_attributes(params[:atividade])
        format.html { redirect_to @atividade, notice: 'Atividade atualizada com sucesso.' }
        format.json { head :no_content }
      else
        format.html {
          flash.now[:error] = @atividade.errors
          render action: "edit"
        }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atividades/1
  # DELETE /atividades/1.json
  def destroy
    @atividade = Atividade.find(params[:id])
    @atividade.destroy

    respond_to do |format|
      format.html { redirect_to atividades_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/inicio_controller.rb
class InicioController < ActionController::Base
  layout "application"

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atividades_helper.rb
module AtividadesHelper
end

app/views/atividades/_form.html.erb
<%= form_for @atividade, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @atividade.errors.size > 0 %>
    <div id="error_explanation">
      <h2>
        <%= @atividade.errors.size %> errors prohibited this <%= @atividade.class.model_name.human %> from being saved:
      </h2>
      <ul>
        <% for message in @atividade.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descricao, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :descricao, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                atividades_path, :class => 'btn' %>
  </div>
<% end %>

app/views/atividades/edit.html.erb
<%- model_class = @atividade.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Editar #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/atividades/index.html.erb
<%- model_class = Atividade.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:usuario) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @atividades.each do |atividade| %>
      <tr>
        <td><%= link_to atividade.id, atividade_path(atividade) %></td>
        <td><%= atividade.nome %></td>
        <td><%= atividade.descricao %></td>
        <td><%= atividade.usuario.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_atividade_path(atividade), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      atividade_path(atividade),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_atividade_path,
            :class => 'btn btn-primary' %>

app/views/atividades/new.html.erb
<%- model_class = @atividade.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "Nova #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/atividades/show.html.erb
<%- model_class = @atividade.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:nome) %>:</strong><br>
  <%= @atividade.nome %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:descricao) %>:</strong><br>
  <%= @atividade.descricao %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:usuario_id) %>:</strong><br>
  <%= @atividade.usuario.email %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              atividades_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_atividade_path(@atividade), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              atividade_path(@atividade),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/inicio/index.html.erb
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Go2</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to "Go2 Teste", root_path, :class => "brand" %>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Cadastrar", new_usuario_registration_path unless usuario_signed_in? %></li>
              <li><%= link_to "Atividades", atividades_path if usuario_signed_in? %></li>

              <li><%= link_to "Login", new_usuario_session_path unless usuario_signed_in? %></li>
            </ul>

            <% if usuario_signed_in? %>
              <div class="container">
                <div class="btn-group" style="float: right;">
                  <a class="btn btn-primary" href="#"><i class="icon-user icon-white"></i> Usuario <%= current_usuario.email %></a>
                  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Editar", edit_usuario_registration_path, :class => "icon-pencil" %></li>
                    <li><%= link_to "Sair", destroy_usuario_session_path, :method => :delete, :class => "icon-share-alt" %></li>
                  </ul>
                </div>
              </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>



    <% if notice %>
      <div class="alert alert-info"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-error"><%= alert %></div>
    <% end %>

    <div class="container">
      <div class="row">
        <div class="span9"><%= yield %></div>
        <div class="span3">
          <h2>Sobre</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
      </div>
    </div>


  </body>
</html>